# vib
name: Cabras Dev Container
id: cabras-dev-container
vibversion: 1.1.0

stages:
  - id: build
    base: debian:stable
    singlelayer: false
    labels:
      maintainer: CabraViva
    args:
      DEBIAN_FRONTEND: noninteractive
    runs:
      commands:
        - >-
          echo 'APT::Install-Recommends "0";' >
          /etc/apt/apt.conf.d/01norecommends
    modules:
      - name: init-setup
        type: shell
        commands:
          #- lpkg --unlock
          - apt-get update

      - name: install-docker
        type: shell
        commands:
          - install -m 0755 -d /etc/apt/keyrings
          - curl -fsSL https://download.docker.com/linux/debian/gpg -o
            /etc/apt/keyrings/docker.asc
          - chmod a+r /etc/apt/keyrings/docker.asc
          - echo \ "deb [arch=$(dpkg --print-architecture)
            signed-by=/etc/apt/keyrings/docker.asc]
            https://download.docker.com/linux/debian bookworm stable" >
            /etc/apt/sources.list.d/docker.list
          - cat /etc/apt/sources.list.d/docker.list
          - apt-get update
          - apt-get install -y docker-ce docker-ce-cli containerd.io
            docker-buildx-plugin docker-compose-plugin

      - name: my-packages
        type: apt
        source:
          packages:
            - ansible
            - ansible-lint
            - bat
            - build-essential
            - cockpit
            - fpart
            - libbz2-dev
            - libdb-dev
            - libffi-dev
            - libffi-dev
            - libgdbm-dev
            - libgmp-dev
            - liblzma-dev
            - libncurses-dev
            - libreadline-dev
            - libreadline6-dev
            - libsqlite3-dev
            - libssl-dev
            - libxml2-dev
            - libxmlsec1-dev
            - libyaml-dev
            - llvm
            - make
            - nginx
            - python3-pip
            - python3-psutil
            - python3-redis
            - tk-dev
            - tree
            - vim
            - zlib1g-dev
      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          #- lpkg --lock
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
          - rm -rf /sources

repo: cabraviva/cabras-dev-container
