# vib
name: Cabras Dev Container
id: cabras-dev-container
vibversion: 1.1.0

stages:
  - id: build
    base: debian:stable
    singlelayer: false
    labels:
      maintainer: CabraViva
    args:
      DEBIAN_FRONTEND: noninteractive
    runs:
      commands:
        - >-
          echo 'APT::Install-Recommends "0";' >
          /etc/apt/apt.conf.d/01norecommends
    modules:
      - name: packages
            type: apt
            source:
              packages:
                - python3
                - neofetch
                - git
                
repo: cabraviva/cabras-dev-container
